name: KnockIt
main: de.spezipaul.knockit.Core
author: Kitt3120
version: 1.0
commands:
  kit:
    description: Kit main command
    usage: /kit
    aliases: [kits, choose, choosekit, items, class, knockit]